---
server:
  port: 8080
  contextPath: /
#spring:
#  profiles:
#    active: ${serverEnv}
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:mem:testdb
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:h2:mem:proddb
    username: myuser
    password: mypassword
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.H2Dialect

